/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vitor.calculadora.java.swing;

/**
 *
 * @author vitor
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtNumero02 = new javax.swing.JTextField();
        btnCalcularSomar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        btnCalcularSubtrair = new javax.swing.JButton();
        btnCalcularDividir = new javax.swing.JButton();
        btnCalcularMultiplicar = new javax.swing.JButton();
        txtNumero01 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Calculadora Básica");

        txtNumero02.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnCalcularSomar.setText("+");
        btnCalcularSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularSomarActionPerformed(evt);
            }
        });

        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setText("Resultado");

        btnCalcularSubtrair.setText("-");
        btnCalcularSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularSubtrairActionPerformed(evt);
            }
        });

        btnCalcularDividir.setText("/");
        btnCalcularDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularDividirActionPerformed(evt);
            }
        });

        btnCalcularMultiplicar.setText("*");
        btnCalcularMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularMultiplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtNumero01, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(txtNumero02, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCalcularSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(btnCalcularSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(btnCalcularMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(btnCalcularDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumero02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularSomar)
                    .addComponent(btnCalcularSubtrair)
                    .addComponent(btnCalcularMultiplicar)
                    .addComponent(btnCalcularDividir))
                .addGap(31, 31, 31)
                .addComponent(lblResultado)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularSomarActionPerformed
        // TODO add your handling code here:  
        Double nota01Convertida = Double.valueOf(txtNumero01.getText());
        Double nota02Convertida = Double.valueOf(txtNumero02.getText());
        
        Double resultadoSoma = nota01Convertida + nota02Convertida;
        lblResultado.setText(resultadoSoma.toString());

    }//GEN-LAST:event_btnCalcularSomarActionPerformed

    private void btnCalcularSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularSubtrairActionPerformed
        // TODO add your handling code here:
        Double nota01Convertida = Double.valueOf(txtNumero01.getText());
        Double nota02Convertida = Double.valueOf(txtNumero02.getText());
        
        Double resultadoSoma = nota01Convertida - nota02Convertida;
        lblResultado.setText(resultadoSoma.toString());
    }//GEN-LAST:event_btnCalcularSubtrairActionPerformed

    private void btnCalcularDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularDividirActionPerformed
        // TODO add your handling code here:
        Double nota01Convertida = Double.valueOf(txtNumero01.getText());
        Double nota02Convertida = Double.valueOf(txtNumero02.getText());
        
        Double resultadoSoma = nota01Convertida / nota02Convertida;
        lblResultado.setText(resultadoSoma.toString());
    }//GEN-LAST:event_btnCalcularDividirActionPerformed

    private void btnCalcularMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularMultiplicarActionPerformed
        // TODO add your handling code here:
        Double nota01Convertida = Double.valueOf(txtNumero01.getText());
        Double nota02Convertida = Double.valueOf(txtNumero02.getText());
        
        Double resultadoSoma = nota01Convertida * nota02Convertida;
        lblResultado.setText(resultadoSoma.toString());
    }//GEN-LAST:event_btnCalcularMultiplicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularDividir;
    private javax.swing.JButton btnCalcularMultiplicar;
    private javax.swing.JButton btnCalcularSomar;
    private javax.swing.JButton btnCalcularSubtrair;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtNumero01;
    private javax.swing.JTextField txtNumero02;
    // End of variables declaration//GEN-END:variables
}
